#include <stdio.h>
#ifdef _WIN32
#include <windows.h> // Sleep() for Windows
#else
#include <unistd.h>  // usleep() for Linux/Mac
#endif

// Function that displays the bits of a variable
void printBits(unsigned int v) {
    for (int i = 31; i >= 0; i--) {
        printf("%d", (v >> i) & 1);
    }
    printf("\r");
}

int main() {
    // Initialising our travel bit (Kitt)
    unsigned int v = 1 << 31;

    while(1) {
        // BIT0 acts as a logic switch to control Kitt's direction (0 for left, 1 for right).
        // This formula toggles the switch based on the state of BIT31 and BIT1.
        v ^= ((v & 0x80000000) >> 31) | ((v & 0x00000002) >> 1);

        // Movement is generated by applying a systematic right shift, counterbalanced by the state of BIT0: (2 & ((1 & v) - 1)).
        // The switch state is preserved/restored after the shift is performed.
        v = (1 & v) | ((v >> 1) << (2 & ((1 & v) - 1)));

        // Print
        printBits(v);
        fflush(stdout);

        // Wait (50ms)
        #ifdef _WIN32
        Sleep(50);
        #else
        usleep(50000);
        #endif
    }
    return 0;
}
